### ISSUE TITLE
Error when selecting multiple mkv files

### ISSUE THREAD

**Issue by Zubaru** [MikeMoolenaar/MkvDefaultTrackChanger#17]
Framework: .NET 8.0.2
RuntimeIdentifier: win-x64
OS: Microsoft Windows 10.0.19045

No mkv file info.

System.IO.IOException: The process cannot access the file 'INSERT FILEPATH' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode)
   at MatroskaLib.MatroskaReader.ReadMkvFiles(String[] filePaths)
   at MatroskaLib.MkvFilesContainer..ctor(String[] filePaths)
   at MkvDefaultTrackChanger.MainForm.LoadFiles()
   at MkvDefaultTrackChanger.MainForm.BtnBrowseFilesClick(Object sender, EventArgs e)

**Comment by MikeMoolenaar** [comment]
> Sorry about the post, error was on my part.

No worries, glad you got it sorted :)
