### ISSUE TITLE
Show better error message when access to file is denied

### ISSUE THREAD

**Issue by PaddyGe** [MikeMoolenaar/MkvDefaultTrackChanger#19]
Framework: .NET 8.0.2
RuntimeIdentifier: win-x64
OS: Microsoft Windows 10.0.26100

{
  "filePath": "",
  "tracks": [
    {
      "trackLengthByteNumber": 4284,
      "number": 1,
      "flagDefault": false,
      "flagDefaultByteNumber": 4303,
      "flagForced": false,
      "flagForcedByteNumber": 0,
      "flagTypebytenumber": 4300,
      "type": "audio",
      "name": "1001cinema",
      "language": "rus"
    },
    {
      "trackLengthByteNumber": 4363,
      "number": 2,
      "flagDefault": false,
      "flagDefaultByteNumber": 0,
      "flagForced": false,
      "flagForcedByteNumber": 0,
      "flagTypebytenumber": 4379,
      "type": "video",
      "name": "",
      "language": "und"
    },
    {
      "trackLengthByteNumber": 4511,
      "number": 3,
      "flagDefault": true,
      "flagDefaultByteNumber": 4530,
      "flagForced": false,
      "flagForcedByteNumber": 0,
      "flagTypebytenumber": 4527,
      "type": "audio",
      "name": "Original",
      "language": "eng"
    },
    {
      "trackLengthByteNumber": 4577,
      "number": 4,
      "flagDefault": false,
      "flagDefaultByteNumber": 4596,
      "flagForced": false,
      "flagForcedByteNumber": 0,
      "flagTypebytenumber": 4593,
      "type": "subtitle",
      "name": "",
      "language": "eng"
    }
  ],
  "seekList": [
    {
      "seekId": 357149030,
      "seekPosition": 4096,
      "seekPositionByteNumber": 70,
      "elementLength": 2
    },
    {
      "seekId": 374648427,
      "seekPosition": 4224,
      "seekPositionByteNumber": 85,
      "elementLength": 2
    },
    {
      "seekId": 475249515,
      "seekPosition": 2833179844,
      "seekPositionByteNumber": 100,
      "elementLength": 4
    },
    {
      "seekId": 307544935,
      "seekPosition": 2833208327,
      "seekPositionByteNumber": 117,
      "elementLength": 4
    },
    {
      "seekId": 272869232,
      "seekPosition": 5746,
      "seekPositionByteNumber": 134,
      "elementLength": 2
    }
  ],
  "seekHeadCheckSum": null,
  "tracksCheckSum": null,
  "voidPosition": 136,
  "endPosition": 4619,
  "tracksPosition": 4282,
  "beginHeaderPosition": 4148
}

System.UnauthorizedAccessException: Access to the path 'T:\S06E01 - Meet The Blacks.mkv' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode)
   at MatroskaLib.MatroskaReader.ReadMkvFiles(String[] filePaths)
   at MatroskaLib.MkvFilesContainer..ctor(String[] filePaths)
   at MkvDefaultTrackChanger.MainForm.LoadFiles()
   at MkvDefaultTrackChanger.MainForm.BtnBrowseFilesClick(Object sender, EventArgs e)

**Comment by MikeMoolenaar** [comment]
This is a permission problem: `Access to the path 'T:\S06E01 - Meet The Blacks.mkv' is denied` and is not the fault of the program. Though I should probably show a friendlier error message :)

**Comment by PaddyGe** [comment]
Also received message: "No mkv file info." in another box-contained text.

**Comment by PaddyGe** [comment]
Hi Mike, you were right (of course ;-) 
Some files had the "Read-only" Attribute set (by the uploader, not by me).
Thank you for you quick response and for this great small program. It helped me change the default language of dozens of files fast and easy.
