### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bigboi1996** [MikeMoolenaar/MkvDefaultTrackChanger#9]
Framework: .NET 8.0.1
RuntimeIdentifier: win-x64
OS: Microsoft Windows 10.0.19045

No mkv file info.

System.UnauthorizedAccessException: Access to the path 'D:\Videos\TV\Fresh Off the Boat\Season 3\Fresh Off the Boat (2015) - S03E01 - Coming from America (1080p AMZN WEB-DL x265 Silence).mkv' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode)
   at MatroskaLib.MatroskaReader.ReadMkvFiles(String[] filePaths)
   at MatroskaLib.MkvFilesContainer..ctor(String[] filePaths)
   at MkvDefaultTrackChanger.MainForm.LoadFiles()
   at MkvDefaultTrackChanger.MainForm.BtnBrowseFilesClick(Object sender, EventArgs e)

**Comment by MikeMoolenaar** [comment]
Looks like a file permission issue. Can you try to open up the application as administrator OR make sure you have the right permissions to that file?

**Comment by bigboi1996** [comment]
Yes tried everything. The problem only occurs for this show and all its seasons.

**Comment by MikeMoolenaar** [comment]
Did you check if you have write permissions? You can check that in the [security tab of the file properties](https://www.thewindowsclub.com/change-files-and-folders-permissions-in-windows-10).
